version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Adafruit
  - asyncread
  - asyncwrite
  - atmega
  - atmelavr
  - atmelsam
  - bargraph
  - Bitfield
  - bitfields
  - cmdcallback
  - configureabm
  - cpppath
  - crwl
  - CSPDR
  - datasheet
  - DBUFFER
  - deviceoff
  - deviceon
  - DIRCLR
  - DNATIVE
  - Doxyfile
  - DSERCOM
  - DSERIALRTT
  - DUNIT
  - DUNITY
  - Enns
  - entrancy
  - espressif
  - fqbn
  - graphviz
  - initialstatus
  - INTB
  - ipch
  - irqcallback
  - ISSI
  - Itest
  - jlink
  - kkostyan's
  - LEDABM
  - ledbox
  - ledon
  - LEDONOFF
  - LEDOPEN
  - LEDPWM
  - LEDSHORT
  - LIBDEPS
  - lockfiles
  - MAINPAGE
  - malloc
  - MDFILE
  - megaatmega
  - Memcpy
  - microcontrollers
  - millis
  - Mobi
  - mutliplies
  - mypy
  - nanoatmega
  - neilenns
  - nordicnrf
  - nullptr
  - onservicecallback
  - osbcallback
  - OUTCLR
  - PAGEDREGISTER
  - pagereg
  - pageselect
  - PARAMDOC
  - PINCFG
  - PIOENV
  - Pmux
  - PMUXEN
  - projenv
  - promicro
  - PSWL
  - PULLUP
  - pycache
  - RRGGBB
  - samd
  - selectpage
  - sendrow
  - SERCOM
  - setcspdr
  - setgcc
  - setimr
  - setpfs
  - setpixelcolor
  - setpixelpwm
  - setrowpwm
  - setswpur
  - simio
  - SIMIOFRAMEWORK
  - sparkfun
  - ststm
  - SWPUR
  - syncread
  - syncwrite
  - Tbegin
  - TINYUSB
  - txns
  - UART
  - UNDOC
  - venv
  - VHDL
  - Werror
  - ZERODMA
ignoreWords: []
import: []
